"""changed thumbnail_urls to thumbnails

Revision ID: de3faf4bc4f4
Revises: e45eb246c42f
Create Date: 2024-03-12 15:37:39.662743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'de3faf4bc4f4'
down_revision = 'e45eb246c42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnails', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('thumbnail_urls')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_urls', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('thumbnails')

    # ### end Alembic commands ###
